project:
  path: C:\CodeFile\JavaProjects\cheesecake-core
  name: cheesecake-core

modules:
  - name: user-service
    path: .\user-service # or absolute path: C:\CodeFile\JavaProjects\cheesecake-core\user-service
    dockerfile_path: C:\CodeFile\JavaProjects\cheesecake-core\user-service\docker\user-dockerfile
    commands:
      local_build: [
        "docker build -t localhost:5000/user-service -f user-dockerfile .",
        "docker push localhost:5000/user-service"
      ]
