project:
    path: C:\CodeFile\JavaProjects\cheesecake-core
    name: cheesecake-core

modules:
  - module:
      name: name
      path: path
      dockerfile_name: name
      local_push_commands: path
      cloud_push_commands: path
